name: Dockerimage Main

on:
  schedule:
    - cron: '0 23 * * *'
  push:
    branches:
      - main
    paths:
      - ".github/workflows/dockerimage-main.yml"
      - "Dockerfile"
      - "startapp.sh"

jobs:
  twitch-drops-miner:
    runs-on: ubuntu-latest
    environment: docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Fetch version tags
        id: fetch_tags
        run: |
          TDM_VERSION_TAG_V=$(curl -s https://api.github.com/repos/c0rrre/TwitchDropsMiner-Alpine/releases/latest | grep -oP '(?<="tag_name": ")[^"]*')
          TDM_VERSION_TAG="${TDM_VERSION_TAG_V#v}"
          echo "TDM_VERSION_TAG=${TDM_VERSION_TAG}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: c0rrre/twitch-drops-miner:latest
          build-args: |
            TDM_VERSION_TAG=${{ env.TDM_VERSION_TAG }}
          pull: true
          no-cache: true

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: c0rrre/twitch-drops-miner
